[package]
name = "aimp-derive"
version = "0.1.0"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.38", features = ["full"] }
proc-macro2 = "1.0.19"
quote = "1.0.7"

[lib]
proc-macro = true
